const state={foreignCash:-1800,foreignFutures:81000,marginBalance:6200,usdtwd:31.5};
const mega=[['2330','台積電'],['2454','聯發科'],['2317','鴻海'],['2308','台達電'],['2382','廣達'],['3711','日月光'],['2303','聯電']];
const etfs=[['00403A','主動統一升級50','4,000','台股權值/成長','每週'],['00406A','主動中信台灣收益','3,000','月配/收益策略','每週'],['00916','國泰全球品牌50','5,000','全球品牌/年配','每週'],['00939','統一台灣高息動能','1,000','高股息/月配','每週']];
const small=[['1304','台聚','4張','塑化低價輪動','看量能/外資/支撐'],['6116','彩晶','2張','面板反彈處理','反彈先減1張'],['1718','中纖','觀察','化纖低價題材','不追高/看量']];
const global=[['SOX','費半','--','--','AI半導體風向'],['NASDAQ','Nasdaq','--','--','科技股風向'],['NVDA','NVIDIA','--','--','AI上游核心'],['MU','Micron','--','--','HBM/記憶體'],['AAPL','Apple','--','--','終端成本壓力'],['META','Meta','--','--','AI CAPEX壓力']];
function pill(text,level){return `<span class="pill ${level}">${text}</span>`}
function riskLevel(score){if(score>=75)return['高風險','red'];if(score>=55)return['震盪','yellow'];return['相對安全','green']}
function calcRisk(){let s=35;if(state.foreignCash<-1000)s+=20;else if(state.foreignCash<0)s+=10;if(state.foreignFutures>80000)s+=20;else if(state.foreignFutures>60000)s+=12;if(state.marginBalance>6000)s+=10;if(state.usdtwd>31.45)s+=12;return Math.min(100,s)}
function render(){document.getElementById('now').textContent='更新時間：'+new Date().toLocaleString('zh-TW');const score=calcRisk();const [title,cls]=riskLevel(score);const el=document.getElementById('riskScore');el.textContent=score;el.className='score '+cls;document.getElementById('riskTitle').textContent=title;document.getElementById('riskText').textContent= score>=75?'外資/空單/匯率偏空，個股避免追高。':score>=55?'震盪盤，ETF底倉可放，中小型股控部位。':'風險較低，可觀察低檔輪動。';
const rows=[['外資現貨',state.foreignCash+' 億',state.foreignCash<-1000?pill('紅','red'):pill('黃','yellow'),'連續大賣=提款壓力'],['外資台指期空單',state.foreignFutures+' 口',state.foreignFutures>80000?pill('紅','red'):pill('黃','yellow'),'8萬口以上=高壓力'],['融資餘額',state.marginBalance+' 億',state.marginBalance>6000?pill('黃','yellow'):pill('綠','green'),'不減反增=散戶槓桿未洗'],['USD/TWD',state.usdtwd,state.usdtwd>31.45?pill('紅','red'):pill('黃','yellow'),'台幣貶=外資匯損壓力'],['0050/台積電','觀察',pill('黃','yellow'),'權值股決定指數'],['日韓/美股','觀察',pill('黃','yellow'),'亞洲資金同步性']];
document.getElementById('macroTable').innerHTML=rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join('');
document.getElementById('summaryBox').innerHTML=[`風險分數：${score}`,score>=75?'策略：個股降槓桿，不追高。':'策略：等回測支撐，分批。','ETF：長期底倉，每週看一次。','中小型：每天看量、價、外資、融資。'].map(x=>`<div>${x}</div>`).join('');
document.getElementById('globalTable').innerHTML=global.map(r=>`<tr><td>${r[0]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td></tr>`).join('');
document.getElementById('megaTable').innerHTML=mega.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>--</td><td>--</td><td>${pill('手動/延遲','yellow')}</td></tr>`).join('');
document.getElementById('etfTable').innerHTML=etfs.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td></tr>`).join('');
document.getElementById('smallTable').innerHTML=small.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td></tr>`).join('');}
document.getElementById('applyBtn').onclick=()=>{state.foreignCash=+foreignCash.value;state.foreignFutures=+foreignFutures.value;state.marginBalance=+marginBalance.value;state.usdtwd=+usdtwd.value;render()};document.getElementById('refreshBtn').onclick=render;render();
